version: '3.9'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./resources/docker/nginx/:/etc/nginx/
      - ./resources/docker/nginx/error/:/var/www/html/error/
      - ./:/var/www/html
networks:
  default:
    name: ITP4506_default